#pragma once

#define WIDTH 400
#define HEIGHT 400

#define BOARD_LOCATION_X 1035
#define BOARD_LOCATION_Y 159
#define BOARD_SIZE 814
#define BOARD_START_SQUIR_X 40
#define BOARD_START_SQUIR_Y 40
#define BOARD_SQUIR_SIZE 40
#define BOARD_ROWS (HEIGHT - (2 * BOARD_START_SQUIR_Y)) / BOARD_START_SQUIR_Y
#define BOARD_COLS (WIDTH - (2 * BOARD_START_SQUIR_X)) / BOARD_START_SQUIR_X
#define BOARD_CIRCLE_MARGIN 5
#define BOARD_INVALID_POSITION -999

#define FONT_FILE_PATH "./assets/fonts/TechnoRaceItalic-eZRWe.otf"

#define SOUND_PUT_ITEM "./assets/sound/itemSound.wav"

#define PLAYER1_COLOR sf::Color::Blue
#define PLAYER2_COLOR sf::Color::Red

#define DRAW_SCORE_BACKGROUND_COLOR sf::Color(0xc4, 0x91, 0x74)
#define DRAW_SCORE_BACKGROUND_MARGIN 2

#define DIALOG_SUCESS_WIDTH 300
#define DIALOG_SUCESS_HEIGHT 100
#define DIALOG_SUCESS_FONT_SIZE 33
#define DIALOG_SUCESS_TOP_MARGIN 26
#define DIALOG_SUCESS_RESET_BUTTON_SIZE sf::Vector2f(50, 30)
#define DIALOG_SUCESS_RESET_BUTTON_MARGIN 5